---
sudo: required
services:
  - docker
env:
  global:
    - "SHA=$(git rev-parse HEAD)"
    - "CLOUDSDK_CORE_DISABLE_PROMPTS=1"
before_install:
  - "openssl aes-256-cbc -K $encrypted_6e1b6df37de9_key -iv $encrypted_6e1b6df37de9_iv -in account-service.json.enc -out account-service.json -d"
  - "curl https://sdk.cloud.google.com | bash > /dev/null;"
  - "source ~/google-cloud-sdk/path.zsh.inc"
  - "gcloud components update kubectl"
  - "gcloud auth activate-service-account --key-file account-service.json"
  - "gcloud config set project tikitakastage"
  - "gcloud config set compute/region us-west2"
  - "gcloud container clusters get-credentials tikitakastage --region=us-west2"
  - "echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin"
  - "docker build -t tikitaka1/general -f ./client/Dockerfile.dev ./client"
deploy:
  provider: script
  script: "bash ./deploy.sh"
  on:
    branch: master


