apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: istio-ab-testing
build:
  artifacts:
  - image: greenteaclassic/tikitaka-prod
deploy:
  kubectl:
    manifests:
    - k8s/tikitaka-app.yaml
